name: Build and Push to GH

on:
  push:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: cloudflaredian
  
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Assign var to ENV
        run: |
          cat ./buildvars >> $GITHUB_ENV
          
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Build and Push image
        run: |
          echo $version
          source ./buildvars ; for n in "${!domains[@]}" ; IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME ; IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]') ; echo IMAGE_ID=$IMAGE_ID ; do docker build --no-cache --build-arg CLOUDFLARED_VERSION=$version --build-arg DOMAIN=${domains[$n]} -t $IMAGE_ID-${domains[$n]}:$version -t $IMAGE_ID-${domains[$n]}:latest . ; docker push --all-tags $IMAGE_ID-${domains[$n]} ; done
          
          
