name: Build and Push to GH

on:
  push:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: cloudflaredian
  
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Assign var to ENV
        run: |
          cat ./buildvars >> $GITHUB_ENV
          
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Build and Push image
        run: |
          for n in "${!domains[@]}" ; do echo "${domains[$n]}" ; done
          
          
